sudo: false

language: ruby
rvm:
  - 2.2

cache:
  bundler: true

before_install:
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./.travis/pr_status pending "Waiting for website to build"; fi'

script:
  - bash .travis/build.sh
before_deploy:
  - bash .travis/pre-deploy.sh

after_success:
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./.travis/pr_deploy; fi'
after_failure:
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then ./.travis/pr_status error "Website failed to build"; fi'

deploy:
  provider: azure_web_apps
  verbose: true
env:
  global:
    - GITHUB_AUTH_USER=allejo
    - GITHUB_USER=CityofSantaMonica
    - GITHUB_REPO=analytics.smgov.net
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
notifications:
  email: false
