language: ruby
cache: bundler
rvm:
  - 2.2
install:
  - export PATH=$HOME/.local/bin:$PATH
  - pip install --user `whoami` virtualenv
script:
  - bash .travis/build.sh
before_deploy:
  - bash .travis/pre-deploy.sh
deploy:
  provider: azure_web_apps
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
