sudo: false
language: python
python:
  - 3.4
cache:
  bundler: true
  pip: true
  directories:
    - _site/pyenv
before_install:
  - rvm install 2.2.5
install:
  - export PATH=$HOME/.local/bin:$PATH
  - pip install virtualenv
script:
  - bash .travis/build.sh
before_deploy:
  - bash .travis/pre-deploy.sh
deploy:
  provider: azure_web_apps
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
