sudo: false

# Because it's easier to switch Ruby versions with rvm installed by default, we'll have Travis
# treat this repo as a Python project so we can easily specify the Python version we want. This
# will also be the version that will be bundled with virtualenv
language: python
python:
  - 3.4

cache:
  bundler: true
  pip: true
  directories:
    - _site/pyenv

before_install:
  # We need Ruby to build the Jekyll site, so setup Ruby 2.2.5 because a Python project has
  # Ruby 1.8.x installed by default
  - rvm install 2.2.5

install:
  - export PATH=$HOME/.local/bin:$PATH
  - pip install virtualenv
script:
  - bash .travis/build.sh
before_deploy:
  - bash .travis/pre-deploy.sh
deploy:
  provider: azure_web_apps
  # use this branch to test the refactor
  on: webjob-refactor
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    # temp azure slot to test the refactor
    - AZURE_WA_SLOT=csmanalytics-stage
